# Generated by Django 3.1.4 on 2020-12-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='temp_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
