# Generated by Django 3.1.4 on 2020-12-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_temp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='temp_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
