# Generated by Django 3.1.4 on 2020-12-20 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201220_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='temp_code',
        ),
    ]
