# Generated by Django 3.1.4 on 2021-01-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_last_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_connection',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
