# Generated by Django 3.1.4 on 2021-01-04 12:37

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210104_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='picture',
            field=models.ImageField(upload_to='', verbose_name=users.models.get_custom_images_path),
        ),
    ]
